### PR TITLE
FS-2824: Set reply to email for fund

### PR DESCRIPTION
**Pull request by Adam-W1**
https://digital.dclg.gov.uk/jira/browse/FS-2824

The reply to email should be a NSTF specific email, not COF.
The email is now passed into the Magic link notification template based on the fund's contact email. 

- [x] Unit tests and other appropriate tests added or updated
- [x] README and other documentation has been updated / added (if needed)
- [x] Commit messages are meaningful and follow good commit message guidelines (e.g. "FS-XXXX: Add margin to nav items preventing overlapping of logo")

### How to test
pytest

### CODE REVIEW

**Review by tferns — DISMISSED** [review]
LGTM, but could we update the example schema to reflect the response changes?

https://github.com/communitiesuk/funding-service-design-notification/blob/69503d7a728127b97f26fe901074b010a91c0cfb/openapi/api.yml#L26-L34

**Comment by tferns** [comment]
@Adam-W1 Have solved conflicts for you and re-ran pip-compiles.  Will re-approve for when you get back this morning 👍

**Review by tferns — APPROVED** [review]

**Comment by Adam-W1** [comment]
> @Adam-W1 Have solved conflicts for you and re-ran pip-compiles. Will re-approve for when you get back this morning 👍

thanks for this @tferns 👍

**Comment by Adam-W1** [comment]
> LGTM, but could we update the example schema to reflect the response changes?
> 
> https://github.com/communitiesuk/funding-service-design-notification/blob/69503d7a728127b97f26fe901074b010a91c0cfb/openapi/api.yml#L26-L34

good shout - adding 👍

**Pull request merged**
